[package]
name = "yi-net"
version = "0.1.0"
edition = "2021"
description = "Yi is a tool for network forwarding"
homepage = "https://github.com/yi-net"
repository = "https://github.com/yi-net/yi"
license = "MIT"

[dependencies]

[[bin]]
name = "yi"
path = "src/main.rs"
